Add GetUser endpoint
gp3ort/CO2Trade pull request #26
Opened 2023-11-13 21:40 UTC by GuidoComp

2023-11-13 22:14 UTC, JonaCaucota requested changes

2023-11-13 22:14 UTC, JonaCaucota commented on CO2Trade-Login-Register/Controllers/EntityUsersController.cs
> +    public async Task<IActionResult> GetUser()
Falta el parametro userId para obtener los datos de ese usuario

2023-11-13 22:17 UTC, JonaCaucota commented on CO2Trade-Login-Register/Controllers/EntityUsersController.cs
> +        }
No es necesario realizar esta validación, ya que por el momento no va a ser necesario que el usuario este autenticado.

2023-11-13 22:20 UTC, JonaCaucota commented on CO2Trade-Login-Register/Repository/IRepository/IEntityUserRepository.cs
> +    Task<EntityUser> GetUser(string userId);
Acá el tipo de dato a devolver debería ser EntityUserDTO para evitar interactuar con un modelo de la bd

2023-11-13 22:22 UTC, JonaCaucota commented on CO2Trade-Login-Register/Repository/EntityUserRepository.cs
> +        .FirstOrDefault(u => u.UserName.ToLower() == loginRequestDTO.BusinessName.ToLower());
No deberiamos interactuar con este flujo. Hagamos rollback en caso de que no se justifique

2023-11-13 22:31 UTC, JonaCaucota commented on CO2Trade-Login-Register/Repository/EntityUserRepository.cs
> +        return await _db.EntityUsers.Include(r => r.Rol).Include(et => et.EntityType).FirstOrDefaultAsync(u => u.Id == userId);
No esta mal pensado el flujo, pero si mal planteado, te dejo una sugerencia en el servicio

2023-11-13 22:35 UTC, JonaCaucota commented on CO2Trade-Login-Register/Service/EntityUsersService.cs
> +            EntityUser user = await _entityUserRepo.GetUser(userId);
La clase EntityUserRepository hereda de Repository<EntityUser> el cual contiene el método Task<T> GetAsync(Expression<Func<T, bool>> filter = null, bool tracked = true), que espera una query y devuelve el tipo de Dato de la implementacion, por lo que se podria usar esto para evitar escribir más codigo, de la sig manera:


```suggestion
    EntityUser user = await _entityUserRepo.GetAsync(x => xId==userId);
```

2023-11-13 22:59 UTC, GuidoComp commented on CO2Trade-Login-Register/Repository/EntityUserRepository.cs
> +        .FirstOrDefault(u => u.UserName.ToLower() == loginRequestDTO.BusinessName.ToLower());
Esto lo agregué porque sino cuando te logueas te devuelve EntityType y Rol en nulo. Lo dejo como estaba antes o se lo dejo?

2023-11-13 23:04 UTC, GuidoComp commented on CO2Trade-Login-Register/Service/EntityUsersService.cs
> +            EntityUser user = await _entityUserRepo.GetUser(userId);
Ahi usé el método heredado y funciona joya. El tema es que no puedo hacer Include de rol y entitytype con ese método, entonces de vuelta, no podemos mostrar el rol y el entity type del user. quizas en este caso se justifica porque es para mostrar los datos del perfil de usuario

2023-11-14 14:14 UTC, JonaCaucota commented on CO2Trade-Login-Register/Service/EntityUsersService.cs
> +            _response.Result = userDto;
podemos reducir estas lineas utilizando el mapper 

```suggestion
        _response.Result = _mapper.Map<EntityUserDTO>(entityUser);

```

2023-11-14 14:14 UTC, JonaCaucota commented on CO2Trade-Login-Register/Repository/EntityUserRepository.cs
> +        .FirstOrDefault(u => u.UserName.ToLower() == loginRequestDTO.BusinessName.ToLower());
Dejemoslo entonces como lo hiciste

2023-11-14 14:16 UTC, JonaCaucota approved these changes

2023-11-14 18:54 UTC, merged